In [1]:
import numpy as np

In [6]:
A=np.array([[0.8,0.3],
           [0.2,0.7]],dtype=float)

x=np.array([1.0,1.0])
x=x/np.linalg.norm(x)

for k in range(1000):
    x=A @ x
    x=x/np.linalg.norm(x)

    print(f"iter {k+1}: {x}")

iter 1: [0.7739573  0.63323779]
iter 2: [0.80417614 0.59439106]
iter 3: [0.81841302 0.57463042]
iter 4: [0.82530726 0.56468392]
iter 5: [0.82869775 0.55969638]
iter 6: [0.83037877 0.55719933]
iter 7: [0.83121572 0.55595002]
iter 8: [0.83163331 0.55532517]
iter 9: [0.83184187 0.5550127 ]
iter 10: [0.8319461  0.55485645]
iter 11: [0.8319982  0.55477832]
iter 12: [0.83202425 0.55473926]
iter 13: [0.83203727 0.55471973]
iter 14: [0.83204378 0.55470996]
iter 15: [0.83204704 0.55470508]
iter 16: [0.83204867 0.55470264]
iter 17: [0.83204948 0.55470142]
iter 18: [0.83204989 0.55470081]
iter 19: [0.83205009 0.5547005 ]
iter 20: [0.83205019 0.55470035]
iter 21: [0.83205024 0.55470027]
iter 22: [0.83205027 0.55470023]
iter 23: [0.83205028 0.55470022]
iter 24: [0.83205029 0.55470021]
iter 25: [0.83205029 0.5547002 ]
iter 26: [0.83205029 0.5547002 ]
iter 27: [0.83205029 0.5547002 ]
iter 28: [0.83205029 0.5547002 ]
iter 29: [0.83205029 0.5547002 ]
iter 30: [0.83205029 0.5547002 ]
iter 31: [0.8320502

In [9]:


# Compute eigenvalues and eigenvectors
eigenvals, eigenvecs = np.linalg.eig(A)
print("Eigenvalues:", eigenvals)
print("Eigenvectors:")
print(eigenvecs)

# Dominant eigenvalue and eigenvector
dominant_idx = np.argmax(np.abs(eigenvals))
dominant_eigenval = eigenvals[dominant_idx]
dominant_eigenvec = eigenvecs[:, dominant_idx]
print(f"\nDominant eigenvalue: {dominant_eigenval}")
print(f"Dominant eigenvector: {dominant_eigenvec}")

# Check if your iterated x matches
print(f"\nYour final x: {x}")
print(f"Matches dominant eigenvector: {np.allclose(x, dominant_eigenvec / np.linalg.norm(dominant_eigenvec))}")

Eigenvalues: [1.  0.5]
Eigenvectors:
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]

Dominant eigenvalue: 1.0
Dominant eigenvector: [0.83205029 0.5547002 ]

Your final x: [0.83205029 0.5547002 ]
Matches dominant eigenvector: True


In [13]:
eig_A=np.linalg.eigvals(A)
eig_A_plus_I=np.linalg.eigvals(A + np.eye(A.shape[0]))
eig_A_sq=np.linalg.eigvals(A @ A)
eig_A_inv=np.linalg.eigvals(np.linalg.inv(A))

print("Eigenvalues of A:      ", eig_A)
print("Eigenvalues of A + I:  ", eig_A_plus_I)
print("Eigenvalues of A^2:    ", eig_A_sq)
print("Eigenvalues of A^-1:   ", eig_A_inv)



Eigenvalues of A:       [1.  0.5]
Eigenvalues of A + I:   [2.  1.5]
Eigenvalues of A^2:     [1.   0.25]
Eigenvalues of A^-1:    [1. 2.]


In [15]:
Ak=np.eye(A.shape[0])
for k in range(1,11):
    Ak=Ak @ A
    print(f"\nA^{k}=\n{Ak}")


A^1=
[[0.8 0.3]
 [0.2 0.7]]

A^2=
[[0.7  0.45]
 [0.3  0.55]]

A^3=
[[0.65  0.525]
 [0.35  0.475]]

A^4=
[[0.625  0.5625]
 [0.375  0.4375]]

A^5=
[[0.6125  0.58125]
 [0.3875  0.41875]]

A^6=
[[0.60625  0.590625]
 [0.39375  0.409375]]

A^7=
[[0.603125  0.5953125]
 [0.396875  0.4046875]]

A^8=
[[0.6015625  0.59765625]
 [0.3984375  0.40234375]]

A^9=
[[0.60078125 0.59882813]
 [0.39921875 0.40117188]]

A^10=
[[0.60039063 0.59941406]
 [0.39960938 0.40058594]]


In [20]:
val,vec=np.linalg.eig(A)
idx=np.argmin(abs(val-1))
pi=vec[:,idx].real
print(pi)
pi=pi/np.sum(pi)
print(pi)

[0.83205029 0.5547002 ]
[0.6 0.4]


In [21]:
P = np.array([[0.2, 0.4, 0.0],
              [0.4, 0.8, 0.0],
              [0.0, 0.0, 1.0]])

print(f"Eigenvalues of P:",np.linalg.eigvals(P))

Eigenvalues of P: [0. 1. 1.]
